// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3rgEK4RyUreP8qsy68v6yTY8zOf__SK4',
    appId: '1:643071376855:web:aa1443669512681219df92',
    messagingSenderId: '643071376855',
    projectId: 'lgsmatematik-fc503',
    authDomain: 'lgsmatematik-fc503.firebaseapp.com',
    storageBucket: 'lgsmatematik-fc503.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcGYXyqcGg-Gy91sWc2CGT1QlzOWtPico',
    appId: '1:643071376855:android:5881c720e5ae2ce619df92',
    messagingSenderId: '643071376855',
    projectId: 'lgsmatematik-fc503',
    storageBucket: 'lgsmatematik-fc503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvlm7iqWYfeqnoZJxp323divKKzPMyx6E',
    appId: '1:643071376855:ios:a3c0f014ca5db2c419df92',
    messagingSenderId: '643071376855',
    projectId: 'lgsmatematik-fc503',
    storageBucket: 'lgsmatematik-fc503.appspot.com',
    iosClientId: '643071376855-lh7o1jofaot3lr19vtv5rjbsa8t7qkba.apps.googleusercontent.com',
    iosBundleId: 'com.example.lgs',
  );
}
